### ISSUE TITLE
`solaire-mode` not loading ? in `emacsclient -c` session

### ISSUE THREAD

**Issue by GaryOma** [hlissner/emacs-solaire-mode#31]
Hi,
I have some issue when trying to open my emacs using the _daemon_ feature.
I seems that `solaire-mode` is nos automatically loading when I open a frame using `emacsclient -c`.

Here you can see : 
![image](https://user-images.githubusercontent.com/9405810/65462159-7c451780-de55-11e9-9907-ca302dffef90.png)

(btw I'm using `doom-city-lights`)

On the left is the emacs run with the `emacs` command, and on the right is the emacs-client run by `emacsclient -c` command. As you can see, `solaire-mode` is not loaded (the colors didn't change & the `Dotfiles` line on `treemacs` should be highlighted).

Running `solaire-mode-reset` don't do anything.

But thanks to [this](https://github.com/magit/magit/issues/3526#issuecomment-408271442) comment, I can run `load-theme` and then choosing `doom-city-lights` again it somehow reloads `solaire-mode` but in the _opposite_ (?) side : the backgrounds are inverted as shown here below : 

![image](https://user-images.githubusercontent.com/9405810/65462625-7b60b580-de56-11e9-8d38-8eada783d48c.png)

I's also pretty nice-looking ^^ but I was wondering if someone had a fix to make this automatically ? Or juste to have `solaire-mode` automatically loading at `emacsclient` startup ?

Thank you !

**Comment by hlissner** [comment]
There are two problems at play here:

1. Your theme (and solaire-mode) are being loaded too soon; this causes solaire's faces to not initialize properly.

2. If the theme is reloaded, you'll find solaire-mode's faces are the wrong way around.


----

You can fix 1 by waiting until the first graphical frame is available. To fix 2, you must call `solaire-mode-swap-bg` (this is necessary for most themes that support solaire-mode):

```elisp
(solaire-globa-mode +1)

(add-hook 'after-make-frame-functions
          (lambda (_frame)
            (load-theme 'doom-city-lights t)
            (solaire-mode-swap-bg))
```

**Comment by GaryOma** [comment]
Hi thank you for your quick answer !

> You can fix 1 by waiting until the first graphical frame is available.

How can I manage to do this ?

> To fix 2, you must call `solaire-mode-swap-bg` (this is necessary for most themes that support solaire-mode)

I tried this solution, and the result is _almost_ working : 

When my config looks like this : 
``` emacs-lisp
(use-package solaire-mode
  :hook
  ((change-major-mode after-revert ediff-prepare-buffer) . turn-on-solaire-mode)
  (minibuffer-setup . solaire-mode-in-minibuffer)
  :config
  (solaire-global-mode +1)
  (add-hook 'after-make-frame-functions
            (lambda (_frame)
              (load-theme 'doom-city-lights t)
              (solaire-mode-swap-bg))))
  ;; (solaire-mode-swap-bg))
```
here are what happens : 

- My _vanilla_ emacs (the one I run with only the `emacs` command) has the colors of `solaire-mode` inverted.
- And for the `emacsclient -c` : 

When I'm launching only one client, I don't have `solaire-mode` working at all : 

![image](https://user-images.githubusercontent.com/9405810/65530797-e8c52280-def8-11e9-87f6-1285783070dc.png)

But, when I'm launching a second client (still using the `emacsclient -c` command), the `solaire-mode` is fixed for **both** the clients : 

![image](https://user-images.githubusercontent.com/9405810/65530935-2924a080-def9-11e9-8732-cc78c95ac17a.png)

Like it applies the fix for the second client & fix the first client at the same time. I can then close one of the client & have a working emacs with a working `solaire-mode`.

**Comment by hlissner** [comment]
I've rewritten solaire-mode in 2be8aa0 to resolve a few performance issues and edge cases, which should indirectly address your issue, if you're still having it (it's been quite a while).

Now, all that's needed is:

```elisp
(use-package solaire-mode
  :config (solaire-global-mode +1))
```

If needed, the bg swapping behavior can still be controlled with the `solaire-mode-auto-swap-bg` variable (or adding themes or regexps to `solaire-mode-themes-to-face-swap`; which is a list of themes to do the swap for).

In any case, it should no longer matter when you load/activate solaire-global-mode, it'll handle those nuances for you.

**Comment by zamlz** [comment]
@hlissner, using the new rewrite of `solaire-mode` but I'm still seeing the same issue. If I start a standalone emacs instance, it works. But if I start a daemon and then spawn client frames, I'm not seeing the intended behaviour. All backgrounds look the same.

**Comment by lucasvreis** [comment]
I also still have the same issue. As a note, the issue happens when starting the daemon in terminal with `emacs --daemon` and then opening `emacsclient`. If I start the daemon by opening the graphical `emacs` then solaire in `emacsclient` works fine.

**Comment by rawhuul** [comment]
@hlissner , I'm facing same issue. You can see in screenshot attached below.

![Screenshot from 2022-02-13 12-47-47](https://user-images.githubusercontent.com/84739019/153743192-fbe67c95-8f16-42dd-8de6-e501f610f5ae.png)

I'm using `doom-wilmersdorf`
