### ISSUE TITLE
Hl-line has the same color as background

### ISSUE THREAD

**Issue by andreyorst** [hlissner/emacs-solaire-mode#35]
It started here https://github.com/hlissner/emacs-doom-themes/issues/488, but I've actually figured out that this happens due to solaire alone. Here's minimal init.el:

<details>
<summary>minimal init.el</summary>

```emacs-lisp
(require 'use-package)

(use-package doom-themes
  :custom
  (doom-themes-enable-bold t)
  (doom-themes-enable-italic t)
  :config
  (load-theme 'doom-one t)
  (set-face-attribute 'highlight nil
                      :foreground 'unspecified
                      :distant-foreground 'unspecified
                      :background 'unspecified))

(use-package solaire-mode
  :commands (solaire-global-mode
             solaire-mode-swap-bg
             turn-on-solaire-mode
             solaire-mode-in-minibuffer
             solaire-mode-reset)
  :hook (((after-revert
           change-major-mode
           org-src-mode) . turn-on-solaire-mode)
         (snippet-mode . solaire-mode))
  :config
  (solaire-mode-swap-bg)
  (with-no-warnings
    (if (boundp 'after-focus-change-function)
        (add-function :after after-focus-change-function #'solaire-mode-reset)
      (add-hook 'focus-in-hook  #'solaire-mode-reset)))
  :init (solaire-global-mode +1))
```
</details>

![image](https://user-images.githubusercontent.com/19470159/84666849-48051000-af2a-11ea-817f-7d1fdb82d779.png)

After running `M-x disable-theme RET solair-swap-bg-theme RET` we get this:

![image](https://user-images.githubusercontent.com/19470159/84666966-6965fc00-af2a-11ea-8042-73ebf0853d6b.png)

**Comment by andreyorst** [comment]
checking out to e077c28 seems to fix the issue, pehaps something to do with 5baf494c78a1f307873072a9dad5703a46e87dd8

**Comment by andreyorst** [comment]
this issue makes treemacs unusable when cursor is turned off

**Comment by andreyorst** [comment]
Also happens in Magit buffers.

**Comment by andreyorst** [comment]
Interestingly, if I `M-x disable-theme RET solaire-swap-bg-theme RET`, and then `M-: (solaire-mode-swap-bg) RET`, then `hl-line` has correct color.

**Comment by seagle0128** [comment]
Is it related to https://github.com/hlissner/emacs-solaire-mode/commit/5baf494c78a1f307873072a9dad5703a46e87dd8?

**Comment by seagle0128** [comment]
It should be related to https://github.com/hlissner/emacs-solaire-mode/commit/5baf494c78a1f307873072a9dad5703a46e87dd8.

My workaround is `(setq solaire-mode-auto-swap-bg t)`.

**Comment by andreyorst** [comment]
> My workaround is (setq solaire-mode-auto-swap-bg t)

Doesn't work for me

**Comment by jakecoble** [comment]
> > My workaround is (setq solaire-mode-auto-swap-bg t)
> 
> Doesn't work for me

Note that this has to be done _before_ your theme is loaded.

**Comment by andreyorst** [comment]
> > > My workaround is (setq solaire-mode-auto-swap-bg t)
> > 
> > 
> > Doesn't work for me
> 
> Note that this has to be done _before_ your theme is loaded.

yes, I know. The background is swapped correctly, but the issue with hl-line is not fixed by adding this.

**Comment by hlissner** [comment]
@andreyorst This appears to be an issue with the `doom-one` theme, rather than solaire-mode, because `doom-dracula` works fine (because [it assigns a different color](https://github.com/hlissner/emacs-doom-themes/blob/master/themes/doom-dracula-theme.el#L138) to `solaire-hl-line-face`). I'll look into it soon.

**Comment by hlissner** [comment]
On second read, the issue was in solaire-mode. As of b6cc22e this issue should be resolved. Two things to keep in mind with this update:

1. Your autoloads file must be loaded before your theme is. i.e. An isolated test won't work without a `(require 'solaire-mode-autoloads)` before the theme is loaded. In the context of normal installation it should work without extra configuration, however.

2. The `solaire-mode-swap-bg` function is now deprecated and does nothing. It was replaced with `solaire-mode-auto-swap-bg` and `solaire-mode-themes-to-face-swap` variables. The former is enabled by default, but the latter will only auto-swap `^doom-*` themes by default.

Let me know if this doesn't address your issue and I'll reopen it. Thanks for bringing it to my attention!

**Comment by seagle0128** [comment]
Thanks for fixing it, @hlissner ! But it seems not working for me. At the first time, hl-line is not displayed. Re-loading the same theme, it's displayed.

The configuration is:

```elisp
(use-package solaire-mode
        :functions persp-load-state-from-file
        :hook (((change-major-mode after-revert ediff-prepare-buffer) . turn-on-solaire-mode)
               (minibuffer-setup . solaire-mode-in-minibuffer))
        :init
        (solaire-global-mode 1)
        (advice-add #'persp-load-state-from-file :after #'solaire-mode-restore-persp-mode-buffers))

(use-package doom-themes
      :init (load-theme 'doom-one t)) ; also for other doom-themes
```

**Comment by seagle0128** [comment]
Thanks for fixing it, @hlissner ! 

But it seems not working for me. At the first time, hl-line is not displayed. Re-loading the same theme, it's displayed.
After my troubleshooting, I found the solution is enabling `hl-line-mode` before loading `solaire-mode`.
The issue still exists.

**Comment by andreyorst** [comment]
doesn't work for me either. I've also made sure that solaire loaded and configured before theme is loaded.

By the way, prior to 5baf494 it was possible to load solaire after theme and it worked just fine. What is the reason to change solaire in a way that requires to load solaire before theme?

**Comment by hlissner** [comment]
cd63b67 removes load order constraints between hl-line and solaire-mode. Please let me know if that fixes your issue.

**Comment by andreyorst** [comment]
> [cd63b67](https://github.com/hlissner/emacs-solaire-mode/commit/cd63b675140232f399e7733d7ce95a0b931b1058) removes load order constraints between hl-line and solaire-mode. Please let me know if that fixes your issue.

Seems working now! Thanks a lot

**Comment by seagle0128** [comment]
I can confirm it's working now. Thank you!
