### ISSUE TITLE
[Bug] Minibuffer does NOT use Evil's emacs state by default.

### ISSUE THREAD

**Issue by ianyepan** [hlissner/emacs-solaire-mode#41]
### Issue type
Bug report

### Environment

Emacs version: GNU Emacs 27.2
Operating System: Windows 10 WSL2 Arch, and Windows 10 WSL2 Ubuntu
Graphical/Terminal: VcXsrv Windows X Server

### My solaire-mode configuration

```emacs-lisp
(use-package solaire-mode
  :config
  (solaire-global-mode +1))
```

### Reproduction steps
- Have both solaire-mode and evil-mode installed
- Start Emacs
- Type a command like M-x or C-x C-f to observe the cursor **being in Evil Normal state in the minibuffer**. Need to enter insert state first before the user can type anything in the minibuffer.
- C-g to quit out of the minibuffer
- Type M-x or C-x C-f again -- the issue is now gone!

### Expected behavior
Minibuffer should always use emacs state by default

### Actual behavior
Minibuffer uses normal state the FIRST time after starting Emacs. From the second time onward, it's good -- it uses emacs state normally.

# Further notes

I initially thought that evil-mode was the package that caused the issue, hence [this discussion](https://github.com/emacs-evil/evil/issues/1465). However, after commenting out my installed packages one by one, I realized that it was solaire-mode causing the minibuffer bug. I suspect it could be due to the big solaire-mode rewrite 2 days ago. Does my description of the issue ring a bell to you?
Thanks in advance, I hope my report could help with finding the issue!

**Comment by hlissner** [comment]
Very strange. I cannot reproduce this. The only possibility is that evil initializes itself in the buffers that `solaire-mode-setup-minibuffer` forward-generates for the minibuffer.

Does this fix your issue?

```elisp
(with-eval-after-load 'solaire-mode
  (defun solaire-mode-setup-minibuffer ()
    (dolist (buf '(" *Minibuf-0*" " *Minibuf-1*"
                   " *Echo Area 0*" " *Echo Area 1*"))
      (with-current-buffer (get-buffer-create buf)
        (if solaire-global-mode
            (when (= (buffer-size) 0)
              (insert " "))
          (erase-buffer))
        (solaire-mode (if solaire-global-mode +1 -1))
        (when (bound-and-true-p evil-mode)
          (evil-emacs-state))))))
```

Also check your \*Messages\* buffer for errors/warnings.

**Comment by ianyepan** [comment]
Thanks for getting back @hlissner , my \*Messages\* buffer contains no relevant information. I've also tried your solution such that my solaire-mode configuration is now:

```emacs-lisp
(use-package solaire-mode
  :config
  (with-eval-after-load 'solaire-mode
    (defun solaire-mode-setup-minibuffer ()
      (dolist (buf '(" *Minibuf-0*" " *Minibuf-1*"
                     " *Echo Area 0*" " *Echo Area 1*"))
        (with-current-buffer (get-buffer-create buf)
          (if solaire-global-mode
              (when (= (buffer-size) 0)
                (insert " "))
            (erase-buffer))
          (solaire-mode (if solaire-global-mode +1 -1))
          (when (bound-and-true-p evil-mode)
            (evil-emacs-state))))))
  (solaire-global-mode +1))
```

But the issue remains.

For the record, this is my evil-mode configuration:

```emacs-lisp
(use-package evil
  :after undo-tree
  :init
  (setq evil-want-C-u-scroll t
        evil-want-keybinding nil
        evil-shift-width ian/indent-width
        evil-undo-system 'undo-tree)
  :hook (after-init . evil-mode)
  :preface
  (defun ian/paste-with-ctrl-shift-v ()
    "Paste with Ctrl-Shift-v, as inspired by Windows Terminal shortcut."
    (interactive)
    (evil-normal-state nil)
    (evil-paste-after 1)
    (evil-insert-state nil)
    (right-char))
  (defun ian/pulse-line ()
    "Flash highlight the current line with reigon face"
    (interactive)
    (pulse-momentary-highlight-one-line (point) 'region))
  :config
  (setq-default cursor-type  '(hbar . 5))
  (setq evil-emacs-state-cursor '(hbar . 5))
  (define-key evil-normal-state-map (kbd "C-w C-o") #'(lambda () (interactive) (neotree-hide) (delete-other-windows)))
  (define-key evil-normal-state-map (kbd "C-o") #'(lambda () (interactive) (evil-jump-backward) (ian/pulse-line)))
  (global-set-key (kbd "C-x 1") #'(lambda () (interactive) (neotree-hide) (delete-other-windows)))
  (global-set-key (kbd "M-<up>") #'(lambda () (interactive) (scroll-down 2)))
  (global-set-key (kbd "M-<down>") #'(lambda () (interactive) (scroll-up 2)))
  (define-key evil-normal-state-map (kbd "M-<left>") #'(lambda () (interactive) (scroll-right 3)))
  (define-key evil-normal-state-map (kbd "M-<right>") #'(lambda () (interactive) (scroll-left 3)))
  (global-set-key (kbd "<mouse-2>") #'mouse-set-point)
  (define-key evil-normal-state-map (kbd "z <return>") #'evil-scroll-line-to-top)
  (define-key evil-insert-state-map (kbd "C-n") nil) ; avoid conflict with company tooltip selection
  (define-key evil-insert-state-map (kbd "C-p") nil) ; avoid conflict with company tooltip selection
  (define-key evil-normal-state-map (kbd "C-p") nil) ; avoid conflict with counsel-find-file
  (define-key evil-normal-state-map (kbd "C-S-c") #'evil-yank)
  (define-key evil-insert-state-map (kbd "C-S-v") #'ian/paste-with-ctrl-shift-v)
  (evil-define-key 'normal prog-mode-map (kbd "gd") #'xref-find-definitions)
  (evil-define-key 'normal prog-mode-map (kbd "<f12>") #'xref-find-definitions)
  (evil-define-key 'normal prog-mode-map (kbd "gD") #'xref-find-references)
  (evil-define-key 'normal prog-mode-map (kbd "S-<f12>") #'xref-find-references)
  (evil-ex-define-cmd "q" #'kill-current-buffer)
  (evil-ex-define-cmd "wq" #'(lambda () (interactive) (save-buffer) (kill-current-buffer)))
  (bind-key* (kbd "<f4>") #'(lambda ()
                              (interactive)
                              (if (one-window-p)
                                  (kill-current-buffer)
                                (kill-buffer-and-window)))))
```

And this is my \*Messages\* buffer after restarting, performing one "M-x", and performing one "C-g":

```text
Loading /home/ianpan/.emacs.d/recentf...done
Cleaning up the recentf list...done (0 removed)
[tree-sitter-langs] Running (git rev-parse --show-toplevel) in /home/ianpan/.emacs.d/elpa/tree-sitter-langs-20210314.1704/
The directory /home/ianpan/.emacs.d/elpa/tree-sitter-langs-20210314.1704/ doesn’t seem to be a git working dir. Grammar-building functions will not work.
tree-sitter-langs: Grammar bundle v0.10.0 was already installed; skipped
Using default formatter emacs-lisp
Package dash-functional is obsolete; use dash 2.18.0 instead
For information about GNU Emacs and the GNU system, type C-h C-a.
Quit
```

**Comment by hlissner** [comment]
I'm afraid I'm at a loss. Using what you've given me of your config so far I cannot reproduce the issue in vanilla Emacs running 27.1, 27.2, or 28, across NixOS, macOS, Arch, or Windows. I'm inclined to suspect it's a private config issue. `solaire-mode-setup-minibuffer` is the only function in this package that remotely touches the minibuffer, and it's touching buffers that you will never directly interact with (where evil isn't enabled).

So unless you have `(setq evil-want-minibuffer t)` elsewhere, or you have the `evil-collection` package installed with `(setq evil-collection-setup-minibuffer t)` somewhere, I don't know where else to look.

**Comment by Zander671** [comment]
I had this same issue on Emacs 27.2-1 on Arch. I fixed it by moving `(require 'evil)` before `(require 'solaire-mode)`.

**Comment by hlissner** [comment]
> I had this same issue on Emacs 27.2-1 on Arch. I fixed it by moving `(require 'evil)` before `(require 'solaire-mode)`.

Order of the `require`s don't make any difference for me (in vanilla Emacs). It is likely something else.

**Comment by ianyepan** [comment]
> So unless you have (setq evil-want-minibuffer t) elsewhere, or you have the evil-collection package installed with (setq evil-collection-setup-minibuffer t) somewhere, I don't know where else to look.

Thanks for the heads-up, though I did make sure I didn't have either of the two setq's. Just now I added `(setq evil-want-minibuffer nil)` and `(setq evil-collection-setup-minibuffer nil)` before loading evil and evil-collection, but the issue still remains...

**Comment by ianyepan** [comment]
> I had this same issue on Emacs 27.2-1 on Arch. I fixed it by moving (require 'evil) before (require 'solaire-mode).

Thanks @Zander671 , since I'm using use-package, I tried your solution by adding the `:after evil` in my solaire-mode config block, yet the issue still remains.

**Comment by ianyepan** [comment]
@hlissner Hi Henrik, I managed to create a super minimal config that **still** shows this issue. For the record, I'm using Emacs 27.2 on Ubuntu 20.04 (Windows 10 WSL2) though X-server VcXsrv.

My minimal config to demo this issue is as follows:

```emacs-lisp
;;; init.el --- -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:
(require 'package)
(add-to-list 'package-archives '("gnu"   . "https://elpa.gnu.org/packages/"))
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-and-compile
  (setq use-package-always-ensure t))

(use-package solaire-mode
  :config
  (solaire-global-mode +1))

(use-package evil
  :hook (after-init . evil-mode))

(provide 'init)
;;; init.el ends here
```

p.s. I've also made sure that my solaire-mode and evil packages are up to date (I uninstalled and reinstalled them).

**Comment by hlissner** [comment]
Finally managed to repro it. `evil-mode` was initializing in those minibuffer buffers `solaire-mode-fix-minibuffer` creates, and does so before it consults `evil-want-minibuffer` (that's why it fixes itself after the first time). I'm inclined to consider this an evil bug, but in any case, 453766f should prevent the issue from now on. Let me know if that isn't the case and I'll reopen this. Thanks for your help debugging the matter and for bringing it to my attention!

**Comment by ianyepan** [comment]
@hlissner Brilliant, thank you very much!
